name: Build ArmorPaint 1.0
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Upgraded to version 20 for better module support

      - name: Generate Project
        # We use --input-type=module to fix the SyntaxError
        run: |
          $makePath = Get-ChildItem -Path . -Filter "make.js" -Recurse | Select-Object -ExpandProperty FullName -First 1
          $content = Get-Content $makePath -Raw
          node --input-type=module -e "$content" -- -g direct3d11

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          $slnPath = Get-ChildItem -Path . -Filter "*.sln" -Recurse | Select-Object -ExpandProperty FullName -First 1
          msbuild $slnPath /p:Configuration=Release /p:Platform=x64

      - name: Prepare Artifact
        run: |
          mkdir out
          $exePath = Get-ChildItem -Path . -Filter "ArmorTools.exe" -Recurse | Select-Object -ExpandProperty FullName -First 1
          copy $exePath out\ArmorPaint.exe
          xcopy /E /I data out\data

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: ArmorPaint-1.0-Windows
          path: out/
